<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>All Contribution venues involved</name>
   <tag></tag>
   <elementGuidId>fa79fba6-6154-4a5d-8764-ebc4bfb97f1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wizard-tabview']/div[2]/div/div/div[2]/div[10]/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.p-multiselect-trigger</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wizard-tabview']/div[2]/div/div/div[2]/div[10]/div/div[3]</value>
      <webElementGuid>ef124f16-1530-46e3-a8ce-034a7b277e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Contribution venues involved'])[1]/following::div[5]</value>
      <webElementGuid>f7ae682a-3e1e-4c09-bcc7-6cfd36871b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contribution type'])[1]/preceding::div[1]</value>
      <webElementGuid>f734e4a7-1e1b-458d-9377-2f9312f5d914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div[3]</value>
      <webElementGuid>99fa71c0-5b96-469c-9abf-e5d0132c7abf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
