<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>APEON_AP_TARGET_div_empty</name>
   <tag></tag>
   <elementGuidId>f7cb4cdc-5d20-4a93-a606-3019b7908c10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wizard-tabview > div.p-tabview-panels > div:nth-child(1) > div > div.main-section-content.p-fluid.grid > div:nth-child(7) > div > div.p-multiselect-label-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wizard-tabview']/div[2]/div/div/div[2]/div[7]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1f45f0ca-9310-4214-b9df-cd1672958954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-multiselect-label-container</value>
      <webElementGuid>efe49922-a75e-44ce-8db0-d71f62293d1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>empty</value>
      <webElementGuid>74c93280-0d83-40a6-be87-a288fb3add83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wizard-tabview&quot;)/div[@class=&quot;p-tabview-panels&quot;]/div[@class=&quot;p-tabview-panel&quot;]/div[@class=&quot;main-section&quot;]/div[@class=&quot;main-section-content p-fluid grid&quot;]/div[@class=&quot;required field col-12 md:col-12&quot;]/div[@class=&quot;p-multiselect p-component p-inputwrapper show-all-label&quot;]/div[@class=&quot;p-multiselect-label-container&quot;]</value>
      <webElementGuid>905e52ab-b97b-48d9-9290-58c933724ff5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wizard-tabview']/div[2]/div/div/div[2]/div[7]/div/div[2]</value>
      <webElementGuid>96353519-b791-4e43-8654-b6f93937476f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AP target audiences'])[1]/following::div[3]</value>
      <webElementGuid>6aa3505f-cf4e-4e3c-9eff-fcc1d53ff7c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End date'])[1]/following::div[4]</value>
      <webElementGuid>8bf279dc-a81e-4097-ac2d-ae3b60019122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AP details/description:'])[1]/preceding::div[3]</value>
      <webElementGuid>2a1acff3-95dd-4196-81be-55136e63c8e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]</value>
      <webElementGuid>369beeeb-6d21-4766-bfe5-9f4c3eff516e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'empty' or . = 'empty')]</value>
      <webElementGuid>f6e2ffec-58ca-4121-a922-36d87a00745d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
