<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Agree</name>
   <tag></tag>
   <elementGuidId>ec4bf23e-74c5-4c29-9d77-610cbe4f602a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.p-button.p-component.p-button-raised.p-button-plain.p-button-sm.hidden-print</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[189]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1c5da863-92c7-4102-8fff-cb9c31183e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component p-button-raised p-button-plain p-button-sm hidden-print</value>
      <webElementGuid>99a9d700-48f7-4828-ad29-f74e185f1556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7dbeb5d1-76a3-4f40-937f-71bf2c68fa74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agree</value>
      <webElementGuid>560cc21c-095e-4bcc-8c32-0eac8e8f1c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;approve-actions2&quot;)/div[@class=&quot;main-section-content p-fluid grid&quot;]/div[@class=&quot;field col-12 md:col-12&quot;]/div[@class=&quot;approval-button&quot;]/div[1]/button[@class=&quot;p-button p-component p-button-raised p-button-plain p-button-sm hidden-print&quot;]</value>
      <webElementGuid>ba8ba839-31de-4c95-a9fd-59e51b713116</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[189]</value>
      <webElementGuid>2c92f8cd-3975-4114-b2f2-0a916d3d53a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='approve-actions2']/div[2]/div[6]/div/div/button</value>
      <webElementGuid>5d230059-1522-401a-b300-834c53ce6c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::button[1]</value>
      <webElementGuid>77da9ee4-fb9f-4992-b80f-42ce0b3a33fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose'])[3]/following::button[1]</value>
      <webElementGuid>e43cd10b-1cb9-4e6a-80c1-bbd7b14935c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Required'])[1]/preceding::button[1]</value>
      <webElementGuid>dedaf8e0-18bb-4a50-abf1-eadd60164588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/button</value>
      <webElementGuid>25f49316-a0f0-4ab8-ae62-328df0b84d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Agree' or . = 'Agree')]</value>
      <webElementGuid>4447581b-1dad-4b3a-8ad8-5509f75f5f44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
