<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit</name>
   <tag></tag>
   <elementGuidId>7fc51d00-646e-4183-9d33-0d27087b2771</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.p-button.p-component</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9f235787-c657-492c-8130-de178a330df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component</value>
      <webElementGuid>38db9b9e-2262-490d-be4f-9723682fa6ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b5fb2d01-7db2-47f5-b825-0075c4e7833b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>e88f71a6-cf33-4a05-814f-d8d25d7cb14b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;layout-wrapper layout-static&quot;]/div[@class=&quot;layout-main-container&quot;]/div[@class=&quot;layout-main&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;mb-none field col-12 md:col-12&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;stepsdemo-content&quot;]/div[@class=&quot;p-card p-component&quot;]/div[@class=&quot;p-card-body&quot;]/div[@class=&quot;p-card-footer&quot;]/div[@class=&quot;grid grid-nogutter justify-content-between&quot;]/button[@class=&quot;p-button p-component&quot;]</value>
      <webElementGuid>c3c5ba40-671a-44ea-ac26-3d2697929901</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>af5fa6d4-97f8-4490-8ef5-fdbdae9a0660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[4]/div/div/div/div/div[2]/div/div/div[3]/div/button</value>
      <webElementGuid>c2220cce-7481-40ab-9f49-09e2bfe8a15d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manager'])[1]/following::button[1]</value>
      <webElementGuid>0c126315-92b9-4a49-89f6-af6ee9916227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Number'])[1]/following::button[1]</value>
      <webElementGuid>d2d3ccdd-e91e-4c2c-a340-e93cb3507958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Casino Regulatory Authority'])[1]/preceding::button[1]</value>
      <webElementGuid>0dc00941-a078-4b7d-8e2b-18ff339728ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>6c198a2e-d016-4285-bf3b-a7853413ac87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>58e01f35-6b8c-4211-aed7-7446329be290</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
