<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SCC_Add_2</name>
   <tag></tag>
   <elementGuidId>0359895e-26f4-40f0-828c-2b5447e1e1e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wizard-tabview > div.p-tabview-panels > div:nth-child(2) > div > div.main-section-content.p-fluid.grid > div > div > div.fileupload-button > button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>#wizard-tabview > div.p-tabview-panels > div:nth-child(2) > div > div.main-section-content.p-fluid.grid > div > div > div.fileupload-button > button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;wizard-tabview&quot;)/div[@class=&quot;p-tabview-panels&quot;]/div[@class=&quot;p-tabview-panel&quot;]/div[@class=&quot;main-section&quot;]/div[@class=&quot;main-section-content p-fluid grid&quot;]/div[@class=&quot;field col-12 md:col-12&quot;]/div[@class=&quot;fileupload-container print-hidden-btn field col-12 md:col-12&quot;]/div[@class=&quot;fileupload-button&quot;]/button[@class=&quot;p-button p-component p-button-raised p-button-sm&quot;][count(. | //*[@class = 'p-button p-component p-button-raised p-button-sm' and @type = 'button' and (text() = 'Add' or . = 'Add')]) = count(//*[@class = 'p-button p-component p-button-raised p-button-sm' and @type = 'button' and (text() = 'Add' or . = 'Add')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>de850dab-6bf3-400d-9805-75f8ab41a72c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component p-button-raised p-button-sm</value>
      <webElementGuid>114a31bf-aaae-40c0-a6bd-55dd15620c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b1fc446c-02fe-4cb3-bc32-a52b5dd13c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>8ae1a179-112e-4bdc-9f66-01682b19cedc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wizard-tabview&quot;)/div[@class=&quot;p-tabview-panels&quot;]/div[@class=&quot;p-tabview-panel&quot;]/div[@class=&quot;main-section&quot;]/div[@class=&quot;main-section-content p-fluid grid&quot;]/div[@class=&quot;field col-12 md:col-12&quot;]/div[@class=&quot;fileupload-container print-hidden-btn field col-12 md:col-12&quot;]/div[@class=&quot;fileupload-button&quot;]/button[@class=&quot;p-button p-component p-button-raised p-button-sm&quot;]</value>
      <webElementGuid>0db8838c-cf36-4431-911f-69a45c2468d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>14bbb64b-492c-462b-83f6-04ff629c294d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component p-button-raised p-button-sm</value>
      <webElementGuid>782157f5-e736-44f6-a3e8-8a5c791d207f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>877240f2-2252-4189-935a-559472482527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>5fe2e937-358c-486d-9971-ddb67b7361a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wizard-tabview&quot;)/div[@class=&quot;p-tabview-panels&quot;]/div[@class=&quot;p-tabview-panel&quot;]/div[@class=&quot;main-section&quot;]/div[@class=&quot;main-section-content p-fluid grid&quot;]/div[@class=&quot;field col-12 md:col-12&quot;]/div[@class=&quot;fileupload-container print-hidden-btn field col-12 md:col-12&quot;]/div[@class=&quot;fileupload-button&quot;]/button[@class=&quot;p-button p-component p-button-raised p-button-sm&quot;]</value>
      <webElementGuid>e2d269a2-acc4-4952-af1b-32468f5ba0f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f7247479-75d5-48ba-93e8-cf72bce12232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component p-button-raised p-button-sm</value>
      <webElementGuid>3e8ef871-0994-4d30-8dae-0735b11ebab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b9f5969d-536e-4c4f-9c63-237fcd85a0a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>743e6320-a4a8-41e4-bab2-376e7d9bfd36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wizard-tabview&quot;)/div[@class=&quot;p-tabview-panels&quot;]/div[@class=&quot;p-tabview-panel&quot;]/div[@class=&quot;main-section&quot;]/div[@class=&quot;main-section-content p-fluid grid&quot;]/div[@class=&quot;field col-12 md:col-12&quot;]/div[@class=&quot;fileupload-container print-hidden-btn field col-12 md:col-12&quot;]/div[@class=&quot;fileupload-button&quot;]/button[@class=&quot;p-button p-component p-button-raised p-button-sm&quot;]</value>
      <webElementGuid>296e6f8b-0497-475e-8af3-d8b016422ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>132dd3f6-a69c-4bb4-980e-d165b0d16127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component p-button-raised p-button-sm</value>
      <webElementGuid>5b1444de-abd5-4dfb-88a1-9caa8c82f593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9c9c1a00-8835-44e3-95d8-34de7c03ddbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>d3cec49a-90a5-4721-833b-505ad7cebd32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wizard-tabview&quot;)/div[@class=&quot;p-tabview-panels&quot;]/div[@class=&quot;p-tabview-panel&quot;]/div[@class=&quot;main-section&quot;]/div[@class=&quot;main-section-content p-fluid grid&quot;]/div[@class=&quot;field col-12 md:col-12&quot;]/div[@class=&quot;fileupload-container print-hidden-btn field col-12 md:col-12&quot;]/div[@class=&quot;fileupload-button&quot;]/button[@class=&quot;p-button p-component p-button-raised p-button-sm&quot;]</value>
      <webElementGuid>f0d86a57-0c4b-4b0d-a7b6-e6e5f205a8e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[7]</value>
      <webElementGuid>d74a8293-f819-42a2-b7c1-8b9124d8c43e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wizard-tabview']/div[2]/div/div[2]/div[2]/div/div/div/button</value>
      <webElementGuid>e1ac9e0d-1fb5-49fa-84ef-4708f07438e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List of Communication Channels'])[1]/following::button[1]</value>
      <webElementGuid>32487e7d-ad04-4486-ad62-32516a3aa39a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publicity/Acknowledgement'])[1]/following::button[1]</value>
      <webElementGuid>e2aaa9ca-8880-4a49-8d45-bf87a2e37adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Communication Channel'])[1]/preceding::button[1]</value>
      <webElementGuid>22ccf0e7-cfd8-4b3d-8aa9-06164aaa6625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button</value>
      <webElementGuid>7e73fd2e-a0c2-4d18-9fe8-b52271c06911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>3ebc9ed4-2463-48ec-917a-8271b6bf999d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
