<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Send to Approver</name>
   <tag></tag>
   <elementGuidId>4f9df621-88e4-41c7-a6cd-095753a9f644</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[249]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ab211513-cb7b-4cb3-a628-eacfa43e4b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component p-button-raised p-button-sm hidden-print</value>
      <webElementGuid>e6b97108-81d6-45e2-b9a1-dcbb81974be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>541fc2b7-3d89-489c-a6b5-9b7556e99244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send to Approver</value>
      <webElementGuid>d05a0ad9-c707-40f8-8a9e-c2d1e0e1ddf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;approve-actions2&quot;)/div[@class=&quot;main-section-content p-fluid grid&quot;]/div[@class=&quot;field col-12 md:col-12&quot;]/div[@class=&quot;approval-button&quot;]/button[@class=&quot;p-button p-component p-button-raised p-button-sm hidden-print&quot;]</value>
      <webElementGuid>2725b703-fa97-4f21-9761-537666121997</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[249]</value>
      <webElementGuid>33f4b5e4-1ec8-4a76-b5ff-51d93ac593b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='approve-actions2']/div[2]/div[7]/div/button</value>
      <webElementGuid>3ed3bb6c-9f36-4131-bc6b-1f9cb916b245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[2]/following::button[1]</value>
      <webElementGuid>e82951dd-d3dd-4749-9920-9636d96eed95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose'])[4]/following::button[1]</value>
      <webElementGuid>e4070f2d-1f0b-4305-905c-f59118906a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Casino Regulatory Authority'])[1]/preceding::button[1]</value>
      <webElementGuid>5c5e786e-3044-4cc5-9b0f-9269bac3e81b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[7]/div/button</value>
      <webElementGuid>14116aa2-472e-47da-8cba-2519f23f75c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Send to Approver' or . = 'Send to Approver')]</value>
      <webElementGuid>1ae75be5-9a56-4fe4-81ae-751a656e60f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
