<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_RecipientsBeneficiaries</name>
   <tag></tag>
   <elementGuidId>f753f768-0285-4fdc-be72-ca2cd337f5c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wizard-tabview > div.p-tabview-panels > div:nth-child(1) > div:nth-child(1) > div.main-section-content.p-fluid.grid > div:nth-child(12) > input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>#wizard-tabview > div.p-tabview-panels > div:nth-child(1) > div:nth-child(1) > div.main-section-content.p-fluid.grid > div:nth-child(12) > input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7c73342c-4077-4039-8dd9-e2124d7bb7b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>inputtext</value>
      <webElementGuid>bd61517c-2e25-4251-9cdd-60ffd6f7c964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recipients/Beneficiaries:</value>
      <webElementGuid>301dfd4e-9a13-448c-8607-cdd01b56cd0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wizard-tabview&quot;)/div[@class=&quot;p-tabview-panels&quot;]/div[@class=&quot;p-tabview-panel&quot;]/div[@class=&quot;main-section&quot;]/div[@class=&quot;main-section-content p-fluid grid&quot;]/div[@class=&quot;field col-12 md:col-12&quot;]/label[1]</value>
      <webElementGuid>d20ab00a-9240-4f17-bded-2f1f9dd32488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>8b6efba5-a6f4-47bb-b8fd-02552cd034cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>inputtext</value>
      <webElementGuid>e6b71d9c-16d1-4d11-b4e2-1e638130d817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recipients/Beneficiaries:</value>
      <webElementGuid>8a162959-5fe1-48f4-9aa9-2d77ecd23ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wizard-tabview&quot;)/div[@class=&quot;p-tabview-panels&quot;]/div[@class=&quot;p-tabview-panel&quot;]/div[@class=&quot;main-section&quot;]/div[@class=&quot;main-section-content p-fluid grid&quot;]/div[@class=&quot;field col-12 md:col-12&quot;]/label[1]</value>
      <webElementGuid>ea902a7b-18c6-4bad-80c9-c30aa77691ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wizard-tabview']/div[2]/div/div/div[2]/div[12]/label</value>
      <webElementGuid>70388a33-614d-4c20-a0d6-5f1b57af7f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Donations'])[1]/following::label[1]</value>
      <webElementGuid>c8fb7f57-cd39-4e8a-8e06-f6274ae23e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contribution type'])[1]/following::label[1]</value>
      <webElementGuid>058c09cb-a601-4e2a-9eb2-7370471e9d47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Items Contributed'])[1]/preceding::label[1]</value>
      <webElementGuid>7faca89d-3581-468e-ae26-cf81dc86fe46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Recipients/Beneficiaries:']/parent::*</value>
      <webElementGuid>3a2a8fbf-bfc7-4d7a-ba98-1120d3af9da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/label</value>
      <webElementGuid>4a771226-7461-4adb-9220-53222bb61048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Recipients/Beneficiaries:' or . = 'Recipients/Beneficiaries:')]</value>
      <webElementGuid>d275832a-c7cf-4f5f-aded-d20012f8fbc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
