<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_SPPLNADPA</name>
   <tag></tag>
   <elementGuidId>846570ab-4cb1-4ba2-a9b0-3c14efcc1177</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wizard-tabview > div.p-tabview-panels > div:nth-child(1) > div > div.main-section-content.p-fluid.grid > div:nth-child(2) > span > input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='pv_id_2_list']/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>6c7b4bc1-5ee4-4e3d-a9ac-dfc7e976d4ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-autocomplete-item</value>
      <webElementGuid>f8bd3e45-7b85-485d-a247-80addc6a1a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e636bc52-bbea-48ac-8aae-262c294a8c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>020a2659-c5d2-4426-b5b2-a4abcc208b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SPPL/NADP/A/220421/0202-TEST APEO</value>
      <webElementGuid>3b6a2aae-05d6-4064-93bd-0a179f201a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_2_list&quot;)/li[@class=&quot;p-autocomplete-item&quot;]</value>
      <webElementGuid>16d28ee9-0847-4ab9-87a8-99da4495173f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pv_id_2_list']/li</value>
      <webElementGuid>8bb4e16f-2844-42fe-b123-30cd6f4d6298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Protection Policy'])[1]/following::li[1]</value>
      <webElementGuid>e4cea4b4-48a5-4b45-98bf-82580e3727c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPPL/NADP/A/220421/0203-TEST APEO'])[1]/preceding::li[1]</value>
      <webElementGuid>32d2fce1-3726-401d-95ef-6c5d822289e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li</value>
      <webElementGuid>97c5064d-839f-459f-a3ab-34b1be07b701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'SPPL/NADP/A/220421/0202-TEST APEO' or . = 'SPPL/NADP/A/220421/0202-TEST APEO')]</value>
      <webElementGuid>b6ac3579-b84f-4135-8f0d-08f6615edf15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
