<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_xinazaas.com</name>
   <tag></tag>
   <elementGuidId>4d52e3da-ecc7-43e4-9e5a-a56bf809e54d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.p-autocomplete-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='pv_id_5_list']/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>9adfde24-c170-48e6-9c1c-efd3c6459d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-autocomplete-item</value>
      <webElementGuid>9aabcd5e-e277-4bf1-8068-f075a04632bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>378a183b-1ae5-4278-add5-baf56e15d6c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a3d34acc-837b-4f1e-90c3-7c03c41c54e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>xin@azaas.com</value>
      <webElementGuid>e9cb79e1-e9a0-4340-ab01-208943b20c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_5_list&quot;)/li[@class=&quot;p-autocomplete-item&quot;]</value>
      <webElementGuid>0f098478-e88f-4dd6-a5d7-d2463772a7b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pv_id_5_list']/li</value>
      <webElementGuid>2254e541-7a76-4e01-9784-c1c95bb50e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Protection Policy'])[1]/following::li[1]</value>
      <webElementGuid>e0a3a52e-7475-4cd2-af9b-1d22d75b5b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[2]/preceding::li[1]</value>
      <webElementGuid>4fb73fe9-e4b1-44b6-83e3-fc4525b7443c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[3]/preceding::li[1]</value>
      <webElementGuid>05eb6435-f308-4e59-af55-6e45f4e7eaf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='xin@azaas.com']/parent::*</value>
      <webElementGuid>246ffa97-8a04-4f08-bc6c-9548a1821226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li</value>
      <webElementGuid>a27dacb8-4cc5-48f3-a4f8-e6f1f7bc3283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'xin@azaas.com' or . = 'xin@azaas.com')]</value>
      <webElementGuid>f8b37dfe-0f1a-4642-9ac2-17e995328603</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
