<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_empty_p-multiselect-trigger-icon pi pi_b2e411_1</name>
   <tag></tag>
   <elementGuidId>04e57387-2c91-4e4c-9f8d-44b2e50fb1cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wizard-tabview']/div[2]/div/div/div[2]/div[7]/div/div[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.p-multiselect-trigger-icon.pi.pi-chevron-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a15ad737-0580-4bcc-b7e1-3278bd026faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-multiselect-trigger-icon pi pi-chevron-down</value>
      <webElementGuid>d78da437-25ba-4f84-aa3d-f8f27530bad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wizard-tabview&quot;)/div[@class=&quot;p-tabview-panels&quot;]/div[@class=&quot;p-tabview-panel&quot;]/div[@class=&quot;main-section&quot;]/div[@class=&quot;main-section-content p-fluid grid&quot;]/div[@class=&quot;required field col-12 md:col-12&quot;]/div[@class=&quot;p-multiselect p-component p-inputwrapper show-all-label&quot;]/div[@class=&quot;p-multiselect-trigger&quot;]/span[@class=&quot;p-multiselect-trigger-icon pi pi-chevron-down&quot;]</value>
      <webElementGuid>26545316-96bf-4b31-b136-4771ee028fff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wizard-tabview']/div[2]/div/div/div[2]/div[7]/div/div[3]/span</value>
      <webElementGuid>eee3fa1a-034d-44d4-8a6c-af6e2562b515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span</value>
      <webElementGuid>9530cf7a-ba5e-422b-bb4a-91684272197a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
